project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Machine Learning Fundamentals"
            file: content/01_journal/Machine Learning Fundamentals.qmd
          - text: "Supervised ML"
            file: content/01_journal/Supervised ML
          - text: "Automated Machine Learning with H2O"
            file: content/01_journal/Automated Machine Learning with H2O.qmd
          - text: "Performance Measures"
            file: content/01_journal/Performance Measures.qmd
          - text: "LIME.qmd"
            file: content/01_journal/LIME.qmd

      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto